package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ActualGrades generated by hbm2java
 */
public class ActualGrades  implements java.io.Serializable {


     private long agId;
     private GradeDetail gradeDetail;
     private Student student;
     private BigDecimal grade;
     private Date GDate;
     private String GDesc;

    public ActualGrades() {
    }

	
    public ActualGrades(long agId, BigDecimal grade, Date GDate) {
        this.agId = agId;
        this.grade = grade;
        this.GDate = GDate;
    }
    public ActualGrades(long agId, GradeDetail gradeDetail, Student student, BigDecimal grade, Date GDate, String GDesc) {
       this.agId = agId;
       this.gradeDetail = gradeDetail;
       this.student = student;
       this.grade = grade;
       this.GDate = GDate;
       this.GDesc = GDesc;
    }
   
    public long getAgId() {
        return this.agId;
    }
    
    public void setAgId(long agId) {
        this.agId = agId;
    }
    public GradeDetail getGradeDetail() {
        return this.gradeDetail;
    }
    
    public void setGradeDetail(GradeDetail gradeDetail) {
        this.gradeDetail = gradeDetail;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public BigDecimal getGrade() {
        return this.grade;
    }
    
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }
    public Date getGDate() {
        return this.GDate;
    }
    
    public void setGDate(Date GDate) {
        this.GDate = GDate;
    }
    public String getGDesc() {
        return this.GDesc;
    }
    
    public void setGDesc(String GDesc) {
        this.GDesc = GDesc;
    }




}


