package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BoardDecisions generated by hbm2java
 */
public class BoardDecisions  implements java.io.Serializable {


     private int bdId;
     private String title;
     private String body;
     private Date DDate;

    public BoardDecisions() {
    }

    public BoardDecisions(int bdId, String title, String body, Date DDate) {
       this.bdId = bdId;
       this.title = title;
       this.body = body;
       this.DDate = DDate;
    }
   
    public int getBdId() {
        return this.bdId;
    }
    
    public void setBdId(int bdId) {
        this.bdId = bdId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }
    public Date getDDate() {
        return this.DDate;
    }
    
    public void setDDate(Date DDate) {
        this.DDate = DDate;
    }




}


