package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ClassStudents generated by hbm2java
 */
public class ClassStudents  implements java.io.Serializable {


     private int csId;
     private Classes classes;
     private Student student;
     private Set finalGradeses = new HashSet(0);

    public ClassStudents() {
    }

	
    public ClassStudents(int csId) {
        this.csId = csId;
    }
    public ClassStudents(int csId, Classes classes, Student student, Set finalGradeses) {
       this.csId = csId;
       this.classes = classes;
       this.student = student;
       this.finalGradeses = finalGradeses;
    }
   
    public int getCsId() {
        return this.csId;
    }
    
    public void setCsId(int csId) {
        this.csId = csId;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Set getFinalGradeses() {
        return this.finalGradeses;
    }
    
    public void setFinalGradeses(Set finalGradeses) {
        this.finalGradeses = finalGradeses;
    }




}


