package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Classes generated by hbm2java
 */
public class Classes  implements java.io.Serializable {


     private int CId;
     private String classDesc;
     private Set classStudentses = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set staffs = new HashSet(0);

    public Classes() {
    }

	
    public Classes(int CId, String classDesc) {
        this.CId = CId;
        this.classDesc = classDesc;
    }
    public Classes(int CId, String classDesc, Set classStudentses, Set schedules, Set staffs) {
       this.CId = CId;
       this.classDesc = classDesc;
       this.classStudentses = classStudentses;
       this.schedules = schedules;
       this.staffs = staffs;
    }
   
    public int getCId() {
        return this.CId;
    }
    
    public void setCId(int CId) {
        this.CId = CId;
    }
    public String getClassDesc() {
        return this.classDesc;
    }
    
    public void setClassDesc(String classDesc) {
        this.classDesc = classDesc;
    }
    public Set getClassStudentses() {
        return this.classStudentses;
    }
    
    public void setClassStudentses(Set classStudentses) {
        this.classStudentses = classStudentses;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


