package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmployeeAttendance generated by hbm2java
 */
public class EmployeeAttendance  implements java.io.Serializable {


     private long eaId;
     private Staff staff;
     private Teacher teacher;
     private Date eaDate;
     private boolean status;
     private Boolean abscent;
     private String abscenceType;
     private Boolean arrive;
     private Boolean leave;
     private String timeAmount;
     private String eaDesc;

    public EmployeeAttendance() {
    }

	
    public EmployeeAttendance(long eaId, Date eaDate, boolean status) {
        this.eaId = eaId;
        this.eaDate = eaDate;
        this.status = status;
    }
    public EmployeeAttendance(long eaId, Staff staff, Teacher teacher, Date eaDate, boolean status, Boolean abscent, String abscenceType, Boolean arrive, Boolean leave, String timeAmount, String eaDesc) {
       this.eaId = eaId;
       this.staff = staff;
       this.teacher = teacher;
       this.eaDate = eaDate;
       this.status = status;
       this.abscent = abscent;
       this.abscenceType = abscenceType;
       this.arrive = arrive;
       this.leave = leave;
       this.timeAmount = timeAmount;
       this.eaDesc = eaDesc;
    }
   
    public long getEaId() {
        return this.eaId;
    }
    
    public void setEaId(long eaId) {
        this.eaId = eaId;
    }
    public Staff getStaff() {
        return this.staff;
    }
    
    public void setStaff(Staff staff) {
        this.staff = staff;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Date getEaDate() {
        return this.eaDate;
    }
    
    public void setEaDate(Date eaDate) {
        this.eaDate = eaDate;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }
    public Boolean getAbscent() {
        return this.abscent;
    }
    
    public void setAbscent(Boolean abscent) {
        this.abscent = abscent;
    }
    public String getAbscenceType() {
        return this.abscenceType;
    }
    
    public void setAbscenceType(String abscenceType) {
        this.abscenceType = abscenceType;
    }
    public Boolean getArrive() {
        return this.arrive;
    }
    
    public void setArrive(Boolean arrive) {
        this.arrive = arrive;
    }
    public Boolean getLeave() {
        return this.leave;
    }
    
    public void setLeave(Boolean leave) {
        this.leave = leave;
    }
    public String getTimeAmount() {
        return this.timeAmount;
    }
    
    public void setTimeAmount(String timeAmount) {
        this.timeAmount = timeAmount;
    }
    public String getEaDesc() {
        return this.eaDesc;
    }
    
    public void setEaDesc(String eaDesc) {
        this.eaDesc = eaDesc;
    }




}


