package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FinalGrades generated by hbm2java
 */
public class FinalGrades  implements java.io.Serializable {


     private int GId;
     private ClassStudents classStudents;
     private Subjects subjects;
     private int grade;
     private Set gradeDetails = new HashSet(0);

    public FinalGrades() {
    }

	
    public FinalGrades(int GId, int grade) {
        this.GId = GId;
        this.grade = grade;
    }
    public FinalGrades(int GId, ClassStudents classStudents, Subjects subjects, int grade, Set gradeDetails) {
       this.GId = GId;
       this.classStudents = classStudents;
       this.subjects = subjects;
       this.grade = grade;
       this.gradeDetails = gradeDetails;
    }
   
    public int getGId() {
        return this.GId;
    }
    
    public void setGId(int GId) {
        this.GId = GId;
    }
    public ClassStudents getClassStudents() {
        return this.classStudents;
    }
    
    public void setClassStudents(ClassStudents classStudents) {
        this.classStudents = classStudents;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public int getGrade() {
        return this.grade;
    }
    
    public void setGrade(int grade) {
        this.grade = grade;
    }
    public Set getGradeDetails() {
        return this.gradeDetails;
    }
    
    public void setGradeDetails(Set gradeDetails) {
        this.gradeDetails = gradeDetails;
    }




}


