package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * GradeDetail generated by hbm2java
 */
public class GradeDetail  implements java.io.Serializable {


     private int gdId;
     private FinalGrades finalGrades;
     private BigDecimal grade;
     private String gradeDetail;
     private Set actualGradeses = new HashSet(0);

    public GradeDetail() {
    }

	
    public GradeDetail(int gdId, BigDecimal grade, String gradeDetail) {
        this.gdId = gdId;
        this.grade = grade;
        this.gradeDetail = gradeDetail;
    }
    public GradeDetail(int gdId, FinalGrades finalGrades, BigDecimal grade, String gradeDetail, Set actualGradeses) {
       this.gdId = gdId;
       this.finalGrades = finalGrades;
       this.grade = grade;
       this.gradeDetail = gradeDetail;
       this.actualGradeses = actualGradeses;
    }
   
    public int getGdId() {
        return this.gdId;
    }
    
    public void setGdId(int gdId) {
        this.gdId = gdId;
    }
    public FinalGrades getFinalGrades() {
        return this.finalGrades;
    }
    
    public void setFinalGrades(FinalGrades finalGrades) {
        this.finalGrades = finalGrades;
    }
    public BigDecimal getGrade() {
        return this.grade;
    }
    
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }
    public String getGradeDetail() {
        return this.gradeDetail;
    }
    
    public void setGradeDetail(String gradeDetail) {
        this.gradeDetail = gradeDetail;
    }
    public Set getActualGradeses() {
        return this.actualGradeses;
    }
    
    public void setActualGradeses(Set actualGradeses) {
        this.actualGradeses = actualGradeses;
    }




}


