package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LectureDatetime generated by hbm2java
 */
public class LectureDatetime  implements java.io.Serializable {


     private int lecId;
     private String lecDay;
     private String lecTime;
     private Set schedules = new HashSet(0);

    public LectureDatetime() {
    }

	
    public LectureDatetime(int lecId, String lecDay, String lecTime) {
        this.lecId = lecId;
        this.lecDay = lecDay;
        this.lecTime = lecTime;
    }
    public LectureDatetime(int lecId, String lecDay, String lecTime, Set schedules) {
       this.lecId = lecId;
       this.lecDay = lecDay;
       this.lecTime = lecTime;
       this.schedules = schedules;
    }
   
    public int getLecId() {
        return this.lecId;
    }
    
    public void setLecId(int lecId) {
        this.lecId = lecId;
    }
    public String getLecDay() {
        return this.lecDay;
    }
    
    public void setLecDay(String lecDay) {
        this.lecDay = lecDay;
    }
    public String getLecTime() {
        return this.lecTime;
    }
    
    public void setLecTime(String lecTime) {
        this.lecTime = lecTime;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }




}


