package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons  implements java.io.Serializable {


     private long PId;
     private String name;
     private String gender;
     private String nationality;
     private String religion;
     private String nationalId;
     private String address;
     private Date dob;
     private Date createdDate;
     private String maritalStatus;
     private Date modifiedDate;
     private Date hiringDate;
     private String qualification;
     private String gradYear;
     private Set contactses = new HashSet(0);
     private Set userses = new HashSet(0);
     private Set students = new HashSet(0);
     private Set teachers = new HashSet(0);
     private Set staffs = new HashSet(0);

    public Persons() {
    }

	
    public Persons(long PId, String name, String gender, String nationality, String religion, String nationalId, String address, Date dob, Date createdDate, Date modifiedDate, Date hiringDate) {
        this.PId = PId;
        this.name = name;
        this.gender = gender;
        this.nationality = nationality;
        this.religion = religion;
        this.nationalId = nationalId;
        this.address = address;
        this.dob = dob;
        this.createdDate = createdDate;
        this.modifiedDate = modifiedDate;
        this.hiringDate = hiringDate;
    }
    public Persons(long PId, String name, String gender, String nationality, String religion, String nationalId, String address, Date dob, Date createdDate, String maritalStatus, Date modifiedDate, Date hiringDate, String qualification, String gradYear, Set contactses, Set userses, Set students, Set teachers, Set staffs) {
       this.PId = PId;
       this.name = name;
       this.gender = gender;
       this.nationality = nationality;
       this.religion = religion;
       this.nationalId = nationalId;
       this.address = address;
       this.dob = dob;
       this.createdDate = createdDate;
       this.maritalStatus = maritalStatus;
       this.modifiedDate = modifiedDate;
       this.hiringDate = hiringDate;
       this.qualification = qualification;
       this.gradYear = gradYear;
       this.contactses = contactses;
       this.userses = userses;
       this.students = students;
       this.teachers = teachers;
       this.staffs = staffs;
    }
   
    public long getPId() {
        return this.PId;
    }
    
    public void setPId(long PId) {
        this.PId = PId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getNationalId() {
        return this.nationalId;
    }
    
    public void setNationalId(String nationalId) {
        this.nationalId = nationalId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Date getHiringDate() {
        return this.hiringDate;
    }
    
    public void setHiringDate(Date hiringDate) {
        this.hiringDate = hiringDate;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public String getGradYear() {
        return this.gradYear;
    }
    
    public void setGradYear(String gradYear) {
        this.gradYear = gradYear;
    }
    public Set getContactses() {
        return this.contactses;
    }
    
    public void setContactses(Set contactses) {
        this.contactses = contactses;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
    public Set getStudents() {
        return this.students;
    }
    
    public void setStudents(Set students) {
        this.students = students;
    }
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }
    public Set getStaffs() {
        return this.staffs;
    }
    
    public void setStaffs(Set staffs) {
        this.staffs = staffs;
    }




}


