package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1



/**
 * ScheduleId generated by hbm2java
 */
public class ScheduleId  implements java.io.Serializable {


     private int suId;
     private int lecId;
     private int TId;
     private int CId;

    public ScheduleId() {
    }

    public ScheduleId(int suId, int lecId, int TId, int CId) {
       this.suId = suId;
       this.lecId = lecId;
       this.TId = TId;
       this.CId = CId;
    }
   
    public int getSuId() {
        return this.suId;
    }
    
    public void setSuId(int suId) {
        this.suId = suId;
    }
    public int getLecId() {
        return this.lecId;
    }
    
    public void setLecId(int lecId) {
        this.lecId = lecId;
    }
    public int getTId() {
        return this.TId;
    }
    
    public void setTId(int TId) {
        this.TId = TId;
    }
    public int getCId() {
        return this.CId;
    }
    
    public void setCId(int CId) {
        this.CId = CId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScheduleId) ) return false;
		 ScheduleId castOther = ( ScheduleId ) other; 
         
		 return (this.getSuId()==castOther.getSuId())
 && (this.getLecId()==castOther.getLecId())
 && (this.getTId()==castOther.getTId())
 && (this.getCId()==castOther.getCId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSuId();
         result = 37 * result + this.getLecId();
         result = 37 * result + this.getTId();
         result = 37 * result + this.getCId();
         return result;
   }   


}


