package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SGLog generated by hbm2java
 */
public class SGLog  implements java.io.Serializable {


     private long SGId;
     private Student student;
     private Subjects subjects;
     private BigDecimal grade;

    public SGLog() {
    }

	
    public SGLog(long SGId, BigDecimal grade) {
        this.SGId = SGId;
        this.grade = grade;
    }
    public SGLog(long SGId, Student student, Subjects subjects, BigDecimal grade) {
       this.SGId = SGId;
       this.student = student;
       this.subjects = subjects;
       this.grade = grade;
    }
   
    public long getSGId() {
        return this.SGId;
    }
    
    public void setSGId(long SGId) {
        this.SGId = SGId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Subjects getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(Subjects subjects) {
        this.subjects = subjects;
    }
    public BigDecimal getGrade() {
        return this.grade;
    }
    
    public void setGrade(BigDecimal grade) {
        this.grade = grade;
    }




}


