package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private int stId;
     private Persons persons;
     private BigDecimal monthlySalary;
     private String status;
     private Set payrolls = new HashSet(0);
     private Set employeeAttendances = new HashSet(0);
     private Set classeses = new HashSet(0);

    public Staff() {
    }

	
    public Staff(int stId, String status) {
        this.stId = stId;
        this.status = status;
    }
    public Staff(int stId, Persons persons, BigDecimal monthlySalary, String status, Set payrolls, Set employeeAttendances, Set classeses) {
       this.stId = stId;
       this.persons = persons;
       this.monthlySalary = monthlySalary;
       this.status = status;
       this.payrolls = payrolls;
       this.employeeAttendances = employeeAttendances;
       this.classeses = classeses;
    }
   
    public int getStId() {
        return this.stId;
    }
    
    public void setStId(int stId) {
        this.stId = stId;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public BigDecimal getMonthlySalary() {
        return this.monthlySalary;
    }
    
    public void setMonthlySalary(BigDecimal monthlySalary) {
        this.monthlySalary = monthlySalary;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPayrolls() {
        return this.payrolls;
    }
    
    public void setPayrolls(Set payrolls) {
        this.payrolls = payrolls;
    }
    public Set getEmployeeAttendances() {
        return this.employeeAttendances;
    }
    
    public void setEmployeeAttendances(Set employeeAttendances) {
        this.employeeAttendances = employeeAttendances;
    }
    public Set getClasseses() {
        return this.classeses;
    }
    
    public void setClasseses(Set classeses) {
        this.classeses = classeses;
    }




}


