package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentAttendance generated by hbm2java
 */
public class StudentAttendance  implements java.io.Serializable {


     private long SAtId;
     private Student student;
     private Date absentDay;
     private String abDesc;
     private Date entryDate;

    public StudentAttendance() {
    }

	
    public StudentAttendance(long SAtId, Date absentDay, Date entryDate) {
        this.SAtId = SAtId;
        this.absentDay = absentDay;
        this.entryDate = entryDate;
    }
    public StudentAttendance(long SAtId, Student student, Date absentDay, String abDesc, Date entryDate) {
       this.SAtId = SAtId;
       this.student = student;
       this.absentDay = absentDay;
       this.abDesc = abDesc;
       this.entryDate = entryDate;
    }
   
    public long getSAtId() {
        return this.SAtId;
    }
    
    public void setSAtId(long SAtId) {
        this.SAtId = SAtId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Date getAbsentDay() {
        return this.absentDay;
    }
    
    public void setAbsentDay(Date absentDay) {
        this.absentDay = absentDay;
    }
    public String getAbDesc() {
        return this.abDesc;
    }
    
    public void setAbDesc(String abDesc) {
        this.abDesc = abDesc;
    }
    public Date getEntryDate() {
        return this.entryDate;
    }
    
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }




}


