package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private long SId;
     private Persons persons;
     private String status;
     private Date ageOnOct;
     private String serialNo;
     private String secretNo;
     private String seatingNo;
     private Set studentExpenseses = new HashSet(0);
     private Set studentAttendances = new HashSet(0);
     private Set SGLogs = new HashSet(0);
     private Set actualGradeses = new HashSet(0);
     private Set classStudentses = new HashSet(0);
     private Set studentNoteses = new HashSet(0);

    public Student() {
    }

	
    public Student(long SId, String status, Date ageOnOct, String serialNo) {
        this.SId = SId;
        this.status = status;
        this.ageOnOct = ageOnOct;
        this.serialNo = serialNo;
    }
    public Student(long SId, Persons persons, String status, Date ageOnOct, String serialNo, String secretNo, String seatingNo, Set studentExpenseses, Set studentAttendances, Set SGLogs, Set actualGradeses, Set classStudentses, Set studentNoteses) {
       this.SId = SId;
       this.persons = persons;
       this.status = status;
       this.ageOnOct = ageOnOct;
       this.serialNo = serialNo;
       this.secretNo = secretNo;
       this.seatingNo = seatingNo;
       this.studentExpenseses = studentExpenseses;
       this.studentAttendances = studentAttendances;
       this.SGLogs = SGLogs;
       this.actualGradeses = actualGradeses;
       this.classStudentses = classStudentses;
       this.studentNoteses = studentNoteses;
    }
   
    public long getSId() {
        return this.SId;
    }
    
    public void setSId(long SId) {
        this.SId = SId;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getAgeOnOct() {
        return this.ageOnOct;
    }
    
    public void setAgeOnOct(Date ageOnOct) {
        this.ageOnOct = ageOnOct;
    }
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }
    public String getSecretNo() {
        return this.secretNo;
    }
    
    public void setSecretNo(String secretNo) {
        this.secretNo = secretNo;
    }
    public String getSeatingNo() {
        return this.seatingNo;
    }
    
    public void setSeatingNo(String seatingNo) {
        this.seatingNo = seatingNo;
    }
    public Set getStudentExpenseses() {
        return this.studentExpenseses;
    }
    
    public void setStudentExpenseses(Set studentExpenseses) {
        this.studentExpenseses = studentExpenseses;
    }
    public Set getStudentAttendances() {
        return this.studentAttendances;
    }
    
    public void setStudentAttendances(Set studentAttendances) {
        this.studentAttendances = studentAttendances;
    }
    public Set getSGLogs() {
        return this.SGLogs;
    }
    
    public void setSGLogs(Set SGLogs) {
        this.SGLogs = SGLogs;
    }
    public Set getActualGradeses() {
        return this.actualGradeses;
    }
    
    public void setActualGradeses(Set actualGradeses) {
        this.actualGradeses = actualGradeses;
    }
    public Set getClassStudentses() {
        return this.classStudentses;
    }
    
    public void setClassStudentses(Set classStudentses) {
        this.classStudentses = classStudentses;
    }
    public Set getStudentNoteses() {
        return this.studentNoteses;
    }
    
    public void setStudentNoteses(Set studentNoteses) {
        this.studentNoteses = studentNoteses;
    }




}


