package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * StudentExpenses generated by hbm2java
 */
public class StudentExpenses  implements java.io.Serializable {


     private long steId;
     private Student student;
     private BigDecimal amount;
     private String steType;
     private Date steDate;

    public StudentExpenses() {
    }

	
    public StudentExpenses(long steId, BigDecimal amount, String steType, Date steDate) {
        this.steId = steId;
        this.amount = amount;
        this.steType = steType;
        this.steDate = steDate;
    }
    public StudentExpenses(long steId, Student student, BigDecimal amount, String steType, Date steDate) {
       this.steId = steId;
       this.student = student;
       this.amount = amount;
       this.steType = steType;
       this.steDate = steDate;
    }
   
    public long getSteId() {
        return this.steId;
    }
    
    public void setSteId(long steId) {
        this.steId = steId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String getSteType() {
        return this.steType;
    }
    
    public void setSteType(String steType) {
        this.steType = steType;
    }
    public Date getSteDate() {
        return this.steDate;
    }
    
    public void setSteDate(Date steDate) {
        this.steDate = steDate;
    }




}


