package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subjects generated by hbm2java
 */
public class Subjects  implements java.io.Serializable {


     private int suId;
     private StudyYears studyYears;
     private String suDesc;
     private String mandatoryFlag;
     private Set finalGradeses = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set teachers = new HashSet(0);
     private Set SGLogs = new HashSet(0);

    public Subjects() {
    }

	
    public Subjects(int suId, String suDesc, String mandatoryFlag) {
        this.suId = suId;
        this.suDesc = suDesc;
        this.mandatoryFlag = mandatoryFlag;
    }
    public Subjects(int suId, StudyYears studyYears, String suDesc, String mandatoryFlag, Set finalGradeses, Set schedules, Set teachers, Set SGLogs) {
       this.suId = suId;
       this.studyYears = studyYears;
       this.suDesc = suDesc;
       this.mandatoryFlag = mandatoryFlag;
       this.finalGradeses = finalGradeses;
       this.schedules = schedules;
       this.teachers = teachers;
       this.SGLogs = SGLogs;
    }
   
    public int getSuId() {
        return this.suId;
    }
    
    public void setSuId(int suId) {
        this.suId = suId;
    }
    public StudyYears getStudyYears() {
        return this.studyYears;
    }
    
    public void setStudyYears(StudyYears studyYears) {
        this.studyYears = studyYears;
    }
    public String getSuDesc() {
        return this.suDesc;
    }
    
    public void setSuDesc(String suDesc) {
        this.suDesc = suDesc;
    }
    public String getMandatoryFlag() {
        return this.mandatoryFlag;
    }
    
    public void setMandatoryFlag(String mandatoryFlag) {
        this.mandatoryFlag = mandatoryFlag;
    }
    public Set getFinalGradeses() {
        return this.finalGradeses;
    }
    
    public void setFinalGradeses(Set finalGradeses) {
        this.finalGradeses = finalGradeses;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getTeachers() {
        return this.teachers;
    }
    
    public void setTeachers(Set teachers) {
        this.teachers = teachers;
    }
    public Set getSGLogs() {
        return this.SGLogs;
    }
    
    public void setSGLogs(Set SGLogs) {
        this.SGLogs = SGLogs;
    }




}


