package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher  implements java.io.Serializable {


     private int TId;
     private Persons persons;
     private BigDecimal monthlySalary;
     private String status;
     private Set payrolls = new HashSet(0);
     private Set subjectses = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set employeeAttendances = new HashSet(0);

    public Teacher() {
    }

	
    public Teacher(int TId, String status) {
        this.TId = TId;
        this.status = status;
    }
    public Teacher(int TId, Persons persons, BigDecimal monthlySalary, String status, Set payrolls, Set subjectses, Set schedules, Set employeeAttendances) {
       this.TId = TId;
       this.persons = persons;
       this.monthlySalary = monthlySalary;
       this.status = status;
       this.payrolls = payrolls;
       this.subjectses = subjectses;
       this.schedules = schedules;
       this.employeeAttendances = employeeAttendances;
    }
   
    public int getTId() {
        return this.TId;
    }
    
    public void setTId(int TId) {
        this.TId = TId;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public BigDecimal getMonthlySalary() {
        return this.monthlySalary;
    }
    
    public void setMonthlySalary(BigDecimal monthlySalary) {
        this.monthlySalary = monthlySalary;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getPayrolls() {
        return this.payrolls;
    }
    
    public void setPayrolls(Set payrolls) {
        this.payrolls = payrolls;
    }
    public Set getSubjectses() {
        return this.subjectses;
    }
    
    public void setSubjectses(Set subjectses) {
        this.subjectses = subjectses;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getEmployeeAttendances() {
        return this.employeeAttendances;
    }
    
    public void setEmployeeAttendances(Set employeeAttendances) {
        this.employeeAttendances = employeeAttendances;
    }




}


