package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserLog generated by hbm2java
 */
public class UserLog  implements java.io.Serializable {


     private long logId;
     private Users users;
     private String logDesc;
     private Date logDate;

    public UserLog() {
    }

    public UserLog(long logId, Users users, String logDesc, Date logDate) {
       this.logId = logId;
       this.users = users;
       this.logDesc = logDesc;
       this.logDate = logDate;
    }
   
    public long getLogId() {
        return this.logId;
    }
    
    public void setLogId(long logId) {
        this.logId = logId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getLogDesc() {
        return this.logDesc;
    }
    
    public void setLogDesc(String logDesc) {
        this.logDesc = logDesc;
    }
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }




}


