package Entity;
// Generated Mar 23, 2018 2:53:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private int UId;
     private Persons persons;
     private String UName;
     private String pass;
     private String status;
     private Date activeDate;
     private String permission;
     private Set userLogs = new HashSet(0);

    public Users() {
    }

	
    public Users(int UId, String UName, String pass, String status, Date activeDate, String permission) {
        this.UId = UId;
        this.UName = UName;
        this.pass = pass;
        this.status = status;
        this.activeDate = activeDate;
        this.permission = permission;
    }
    public Users(int UId, Persons persons, String UName, String pass, String status, Date activeDate, String permission, Set userLogs) {
       this.UId = UId;
       this.persons = persons;
       this.UName = UName;
       this.pass = pass;
       this.status = status;
       this.activeDate = activeDate;
       this.permission = permission;
       this.userLogs = userLogs;
    }
   
    public int getUId() {
        return this.UId;
    }
    
    public void setUId(int UId) {
        this.UId = UId;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public String getUName() {
        return this.UName;
    }
    
    public void setUName(String UName) {
        this.UName = UName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getActiveDate() {
        return this.activeDate;
    }
    
    public void setActiveDate(Date activeDate) {
        this.activeDate = activeDate;
    }
    public String getPermission() {
        return this.permission;
    }
    
    public void setPermission(String permission) {
        this.permission = permission;
    }
    public Set getUserLogs() {
        return this.userLogs;
    }
    
    public void setUserLogs(Set userLogs) {
        this.userLogs = userLogs;
    }




}


